version: '3.8'

services:
  express-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_PORT}:3000"
    volumes:
      - ./app:/usr/src/app # Mount local code into the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    env_file:
      - .env 
    restart: always
    command: nodemon index.js # Use nodemon for live updates

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin configuration
    depends_on:
      - db
    restart: always